spring:
  cloud:
    gateway:
      routes:
        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/login/**
          filters:
            - StripPrefix=1
        - id: test-service
          uri: lb://test-service
          predicates:
            - Path=/test/**
            - Path=/test-service/**
          filters:
            - StripPrefix=1